### ISSUE TITLE
process returns 0 (as success) even if the protractor fails to pass the tests on retries

### ISSUE THREAD

**Issue by jardakotesovec** [yahoo/protractor-retry#21]
First of all, thanks for this package. Its super helpful.

Just noticed on our circleCI that even if retry fails, it's considered passing. Main process seems to just ends when spawned processes ends, without trying to communicate the result via process.exit.

I should be able to investigate this tomorrow more thoroughly and ideally with some PR. As this is big deal and wondering how you use it that you don't have this problem.

**Comment by amrot17** [comment]
Good to know that the Package is Helping you 
if i got your point correctly , This maybe a Reporting issue that you need to handle from your Own ( if you are generating any report files ) 

and your more than welcome to submit a solution that could improve this

**Comment by dreuxl** [comment]
https://github.com/yahoo/protractor-retry/pull/29 should fix it
