### ISSUE TITLE
E/launcher - Error: TypeError: retry.afterLaunch is not a function

### ISSUE THREAD

**Issue by premkh9** [yahoo/protractor-retry#26]
While trying to execute protractor config.js file, I am seeing below mentioned error. Can you please help me to understand what is causing this issue

[11:57:19] E/launcher - Error: TypeError: retry.afterLaunch is not a function

**Comment by amrot17** [comment]
@premkh9 If you please `gist` your `config.js` file so i can debug the issue for you 

Thanks

**Comment by chadatslalom** [comment]
I changed the following line
const retry = require('protractor-retry'); 
to:
const retry = require('protractor-retry').retry;

It started working.

**Comment by SirDirtClod** [comment]
@chadatslalom Thanks for the reply! We ended up using [another library](https://github.com/NickTomlin/protractor-flake) instead which doesn't require editing the protractor config file. I'll keep this in mind if we decide to switch back.
