### ISSUE TITLE
Error: spawn EACCES while rerunning the failed tests using protractor-retry

### ISSUE THREAD

**Issue by NP33** [yahoo/protractor-retry#28]
I am getting the following error while rerunning the failed tests in protractor using protractor-retry, i am running the tests in browserstack.
11:07:08] E/launcher - Error: { Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at /Users/usename/.nvm/versions/node/v6.9.0/lib/node_modules/protractor-retry/lib/retry.js:145:38
    at Function.promise (/Users/username/node_modules/q/q.js:702:9)
    at /Users/username/.nvm/versions/node/v6.9.0/lib/node_modules/protractor-retry/lib/retry.js:144:18
    at Promise.apply (/Users/username/node_modules/q/q.js:1185:26)
    at Promise.promise.promiseDispatch (/Users/username/node_modules/q/q.js:808:41)
    at /Users/username/node_modules/q/q.js:1411:14
    at runSingle (/Users/username/node_modules/q/q.js:137:13) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
[11:07:08] E/launcher - Process exited with error code 1

My environment is: 
node version: 6.9,
protractor: 5.3.0
framework: jasmine2
java: 9.0.4

And my config file is as below: 

`'use strict';

var browserstack = require('browserstack-local');
var retry = require('protractor-retry').retry;

exports.config = {

    seleniumAddress: 'http://hub-cloud.browserstack.com/wd/hub',

    'commonCapabilities': {
        'browserstack.local': true,
        'browserstack.user': 'my username',
        'browserstack.key': 'mypassword'
    },

    multiCapabilities: [
        
        {
             'os': 'Windows',
             'os_version': '8.1',
             'browserName': 'IE',
             'version': 11
         },
        {
            'os': 'Windows',
            'os_version': '10',
            'browserName': 'Edge',
            'browser_version': '16',
            'maxInstances': 4
        }
    ],

    allScriptsTimeout: 600000,
    getPageTimeout: 1200000,

    maxSessions: 1,

    params: {
        route: 'my url'
    },

    jasmineNodeOpts: {
        defaultTimeoutInterval: 900000,
        showColors:             true,
        showTiming:             true,
        includeStackTrace:      true,
        isVerbose:              true,
        realtimeFailure:        true,
        print: function() {
        }
    },

    framework: 'jasmine2',

    rootElement: 'body',

    // Code to start browserstack local before start of test
    beforeLaunch: function() {
        console.log('Connecting local');
        return new Promise(function (resolve, reject) {
            exports.bs_local = new browserstack.Local();
            exports.bs_local.start({'key': exports.config.commonCapabilities['browserstack.key'], 'force': true}, function (error) {
                if (error) {
                    console.log(error.message);
                    return reject(error);
                }
                console.log('Connected. Now testing...');
                resolve();
            });
        });
    },

    onPrepare: function() {

        retry.onPrepare();

        browser.driver.manage().window().maximize();
        browser.driver.getCapabilities().then(function(caps){
            browser.browserName = caps.get('browserName');
        });

        var jasmineReporters = require( 'jasmine-reporters' );
        jasmine.getEnv().addReporter( new jasmineReporters.JUnitXmlReporter( {
            consolidateAll: true,
            savePath:       'testresults',
            filePrefix:     'xmloutput'
        } ) );

        var SpecReporter = require( 'jasmine-spec-reporter' ).SpecReporter;
        jasmine.getEnv().addReporter( new SpecReporter( {
            displayStacktrace:      true,
            displayFailuresSummary: true,
            displayPendingSummary:  true,
            displaySuccessfulSpec:  true,
            displayFailedSpec:      true,
            displayPendingSpec:     true,
            displaySpecDuration:    false,
            displaySuiteNumber:     false,
            colors: {
                success: 'green',
                failure: 'red',
                pending: 'yellow'
            },
            customProcessors: []
        } ) );

        browser.driver.get( browser.params.route);

        //I am injecting some cookie here
        browser.manage().addCookie({name:'session_id', value: '2'});
        browser.manage().addCookie({name:'badges', value: 'false'});

        //I have more cookie injection here

        browser.get( browser.params.route );
        browser.waitForAngular();

        return;
    },

    // Code to stop browserstack local after end of test
    afterLaunch: function() {

        return retry.afterLaunch(2);

        return new Promise(function (resolve) {
            exports.bs_local.stop(resolve);
            console.log('Stopping...');
        });
    },

    //code to rerun failed tests
    onCleanUp: function(results) {
        retry.onCleanUp(results);
    }

};

// Code to support common capabilities
exports.config.multiCapabilities.forEach(function(caps){
    for(var i in exports.config.commonCapabilities) caps[i] = caps[i] || exports.config.commonCapabilities[i];
});

I have many tests failing while running them in a group suites and want to rerun the failed tests until they pass. Can you please help me how to resolve this issue.
`

**Comment by dreuxl** [comment]
Hi

thanks for using the pkg.

Q: Are u running your Command from a windows machine? 

thanks

**Comment by NP33** [comment]
Thank you so much for responding so quickly. I am really grateful to you. I am running command from mac and running tests in windows in browserstack.

**Comment by dreuxl** [comment]
ok

so thats not what I thought :) (we don't support windows yet).

Can u run the cmd with sudo to check if it s still happening.

check out this thread here for instance, it seems similar to what u have 
https://github.com/mikaelbr/gulp-notify/issues/112 
It may also be due to your node version, even though we should support it.

lmk how it goes

**Comment by NP33** [comment]
Sure, i will try and update here.

**Comment by NP33** [comment]
I have installed protractor-retry  package with 'sudo npm i -g  protractor-retry' and i am still getting the same error after rerunning the failed tests.

**Comment by NP33** [comment]
And my current framework only allow me to use node version 6.9.0.

**Comment by dreuxl** [comment]
ok :( 

and u run your protractor command with sudo as well?

**Comment by NP33** [comment]
oh, I was running the test from webstorm and now i tried running it from terminal, now it is working when i used sudo in front of protractor command, but i still need it to run my tests from webstorm in browserstack, is there any way for it?  Thanks a bunch.

**Comment by dreuxl** [comment]
ok

I don't know much about Webstorm, but this IDE is probably managing is own execution privileges compare to the command line launch. u should check around those privileges settings within your IDE (check that it remains executable for instance)

Hope this helps
