### ISSUE TITLE
How to rerun only failed test, not all spec

### ISSUE THREAD

**Issue by igorek845** [yahoo/protractor-retry#34]
For example, tests Running in Parallel mode. I have 2 tests in one spec, one test passed, another failed. Will be rerun all tests in spec.
How make rerun only failed tests?

**Comment by amrot17** [comment]
This is not supported in our module as its not that straightforward with protractor to run a single test in a spec .

Like if you are using mocha you need to add a unique string in the ‘it’ function and use ‘mocha grep’

**Comment by dreuxl** [comment]
it should be supported with v 1.2.0 . give it a shot.
Thanks
Please reopen this one if it s still NOK
