### ISSUE TITLE
Failed testcase is re-run twice

### ISSUE THREAD

**Issue by laflaneuse** [yahoo/protractor-retry#35]
Issue description : when a testcase fails during the first run, then each re-run triggers it twice. Additionally the whole spec is re-triggered but this is already covered in #34.

Relevant protractor configuration :
    shardTestFiles: true,
    maxInstances: 8

Protractor version : 5.2.0
Protractor-retry version : 1.1.9

Logs :

build	16-Apr-2018 12:28:46	[chrome #01-2]     Navigation
build	16-Apr-2018 12:28:46	[chrome #01-2]       ✓ should be on "Overview"
build	16-Apr-2018 12:28:46	[chrome #01-2]       ✗ should include a random-fail step
build	16-Apr-2018 12:28:46	[chrome #01-2]         - Expected true to be false.
build	16-Apr-2018 12:28:46	[chrome #01-2]             at UserContext.<anonymous> (/some_path/some-view.e2e-spec.ts:34:22)
build	16-Apr-2018 12:28:46	[chrome #01-2]             at /aw/node_modules/jasminewd2/index.js:112:25
build	16-Apr-2018 12:28:46	[chrome #01-2]             at new ManagedPromise (/aw/node_modules/selenium-webdriver/lib/promise.js:1077:7)
..................
build	16-Apr-2018 12:45:03	 Re-running tests , attempt :  1
build	16-Apr-2018 12:45:03	 Re-running the following test files : /some_path/some-view.e2e-spec.ts
.....
build	16-Apr-2018 12:45:44	[10:45:44] I/testLogger - [chrome #01-3] PID: 314
build	16-Apr-2018 12:45:44	[chrome #01-3] Specs: /some_path/some-view.e2e-spec.ts
--> runs green and in the same re-run the same test is triggered one more time

build	16-Apr-2018 12:45:50	[10:45:50] I/testLogger - [chrome #01-0] PID: 301
build	16-Apr-2018 12:45:50	[chrome #01-0] Specs: /some_path/some-view.e2e-spec.ts
--> runs green again

**Comment by dreuxl** [comment]
Hi

I m not clear about your issue here :(
there is an extra re run not needed in your case?
which os are u running on ? can u share a gist of the whole output of your Command Line, it will be helpful for first debugging/understanding.

Thanks
Ludo

**Comment by dreuxl** [comment]
"Additionally the whole spec is re-triggered but this is already covered in #34" 

This part should be with 1.2.0 version, give it a shot

Thanks

**Comment by laflaneuse** [comment]
Update on this issue : we tried out version 1.2.0 and we still had the same behavior. The whole testsuite would be re-triggered and each failed testcase would be called twice in each-run.
We have solved this in between, this is what worked for us : 
Initial protractor configuration
exports.config = {
  allScriptsTimeout: 15000,
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        '--headless',
        '--disable-gpu',
        '--window-size=1200x800'
      ]
    },
    **specs: './src/main/angular/**/*.e2e-spec.ts',**
    shardTestFiles: true,
    maxInstances: 8
  },

New version where the problem is solved
exports.config = {
  allScriptsTimeout: 15000,
  **specs: './src/main/angular/**/*.e2e-spec.ts',**
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        '--headless',
        '--disable-gpu',
        '--window-size=1200x800'
      ]
    },
    shardTestFiles: true,
    maxInstances: 8
  },

As you can see, we just moved the specs outside the capabilities section. Maybe this is of use to someone else as well.
I believe we can close this now, many thanks for your assistance!
