### ISSUE TITLE
Chrome crashes are treated as success in 1.1.9

### ISSUE THREAD

**Issue by khitrenovich** [yahoo/protractor-retry#40]
We run `protractor-retry` on sharded specs in sequence with the following configuration:
```
  capabilities: {
    'browserName': 'chrome',
    'shardTestFiles': true, // with shard, we can retry individual specs
    'maxInstances': 1,
    ...
  }
```

It appears that if Chrome crashes on one of the specs (see example in #25), `protractor-retry` treats that as success and marks all tests as passed. This is a regression since it worked fine in v1.1.8 and is broken now.

**Comment by khitrenovich** [comment]
Possible cause: https://github.com/yahoo/protractor-retry/pull/29/files#r185912791

**Comment by khitrenovich** [comment]
How can I see the return code? Is it logged somewhere?

**Comment by dreuxl** [comment]
it s available in when you run your Cmd in debug mode, ie

`DEBUG=* yourprotractorcmd`

**Comment by khitrenovich** [comment]
Thanks, I'll check how can I set this up in our CI environment.
Unfortunately, this env goes through some major upgrade now, so next week is the earliest...

**Comment by khitrenovich** [comment]
I haven't seen Chrome crashes for long time, and I don't know how to force-crash it.
Going to close the issue for now.
