### ISSUE TITLE
Unable to rerun failed test cases in protractor on window machine

### ISSUE THREAD

**Issue by akagupta9** [yahoo/protractor-retry#59]
It is giving following error - 
E/Launcher : spawn node-modules\protractor\bin\protractor
Error: spawn node-modules\protractor\bin\protractor
 at process.childprocess._handle.onexit

**Comment by dreuxl** [comment]
Hi
Look like you are using a Windows machine, unfortunately it s not yet supported as mentioned in the README

**Comment by tbowmo** [comment]
@dreuxl if we finish up #16 we could have windows as a supported platform.

Will you accept a PR, if I make a new one (In case you are abandoning the one in #16)

**Comment by dreuxl** [comment]
I need to get the hand on my windows machine and finish up the #16 with the suggested bump of cross-spawn version.
will your PR be different approach that #16? if yes, please go for it

**Comment by tbowmo** [comment]
@dreuxl looked at the patch we're using, and it's basically what is outline in my comments in #16

We are using it actively in production now, with windows based buildagents hosted in azure.

**Comment by dreuxl** [comment]
2.0.1 version should support windows now
