### ISSUE TITLE
Can this be updated to work with suites instead of specs?

### ISSUE THREAD

**Issue by emaxsaun** [yahoo/protractor-retry#7]
Can this be updated to work with suites instead of specs? I have a project that uses suites, but when I use suites, if there is one failure, all tests will re-run, even in parallel, but when I change to specs, it works fine, but that is not an ideal solution for me. Please let me know, thanks.

**Comment by dreuxl** [comment]
I m not sure to understand correctly your point here? is that still a pb?

Even if you specify testsuite, behind the scene, that should be only a list of spec files, and that s this list that we used to extract the files to replay.

That doesn t work for you? 
Can you give us more infos, gist link of output with your command line?

thanks

**Comment by emaxsaun** [comment]
In our project we launch protractor using:

`./flake protractor.conf.js --suite=${SUITE} --baseUrl=${ENV}`

These are passed in using Jenkins.

We have the suites defined in our protractor conf file in a `suites: {}` block, with the individual tests there, yes, just like specs, but we also have some sub suites listed out like:

`ny_regressions: ['test1','test2','test3']`

I'm more familiar with using suites like this, but if we could re-write this to use specs in this way and pass them in via the command line, I could re-write our tests this way, and this would end up not being an issue. 

Thank you for replying and thank you in advance for any insight you can provide here.

**Comment by dreuxl** [comment]
ok 

valid issue sir.
https://github.com/yahoo/protractor-retry/pull/10 should fix it.

thanks for the feedback

**Comment by emaxsaun** [comment]
Np, thank you very much! This should work for our use case! Testing now!

**Comment by emaxsaun** [comment]
I just tested again and it works, thank you again! :)

**Comment by dreuxl** [comment]
thanks to you man. 

Appreciated such feedback, very useful for us as well.
Happy testing and don t hesitate to spread the word!! ;)

**Comment by emaxsaun** [comment]
Np! I will! :)
