### ISSUE TITLE
git Refusing to remove it

### ISSUE THREAD

**Issue by premkh9** [yahoo/protractor-retry#72]
$ npm install
npm ERR! code EISGIT
npm ERR! path .............................................\node_modules\protractor-retry
npm ERR! git ..................................................\node_modules\protractor-retry: Appears to be a git repo or submodule.
npm ERR! git .........................................................................\node_modules\protractor-retry
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

started seeing this after latest update (3 days)

**Comment by DenysVuika** [comment]
I can confirm that, there's a mistake in publishing to NPM I believe: https://unpkg.com/browse/protractor-retry@1.2.11/. There should not be a `.git` folder in there.

**Comment by dreuxl** [comment]
Not good :( ... looking

**Comment by premkh9** [comment]
Thank you @dreuxl . Appreciate your help

**Comment by premkh9** [comment]
@dreuxl Did you get a chance to fix the changes? Latest changes are causing npm install to fail

**Comment by defremovSFX** [comment]
We have the same problem

**Comment by dreuxl** [comment]
not yet.

**Comment by Morcatko** [comment]
1.2.9 worked, but 1.2.10 already contains .git folder.
You can use `npm pack protractor-retry@version` - this will download the package from npm without extracting so that you can inspect it.

**Comment by ajaysuwalka** [comment]
Man, Do you understand the impact of using this in production, You are not able to do a checkout and publish it again? Do you really care? It's been more than 15 days.

**Comment by Morcatko** [comment]
> Man, Do you understand the impact of using this in production, You are not able to do a checkout and publish it again? Do you really care? It's been more than 15 days.

I am not a contributor to this project, but this comment sounds quite rude to me. It is free and open-source. You don't have to use it. You can fork it or even better you can make PR with a fix.

Btw finding a workaround is ~2 mins of googling - replace version in package.json with git url
`"protractor-retry": "git+https://github.com/linhub15/protractor-retry.git"`

**Comment by ajaysuwalka** [comment]
I am sorry for the rude comment but this has broken many production builds. This is known to author that builds are breaking and still, it's not fixed. I've also fixed but everyone has to go and then fix it. How much time does it take?

**Comment by dreuxl** [comment]
please give a shot to latest 1.2.12 version

`rude` was an euphemism here @Morcatko

**Comment by ajaysuwalka** [comment]
> please give a shot to latest 1.2.12 version
> 
> `rude` was an euphemism here @Morcatko, thanks for your support.

Ok, I apologize! Probably I couldn't figure out a better expression to explain my frustration when of my several production builds failed and created panic. If all the open-source code start failing like this and the package owner doesn't fix them even after knowing, This entire open-source user base will have sleepless nights.

**Comment by ajaysuwalka** [comment]
1.2.12 Works fine.

**Comment by dreuxl** [comment]
thanks for confirming
