### ISSUE TITLE
Getting retry to work in Jenkins

### ISSUE THREAD

**Issue by emaxsaun** [yahoo/protractor-retry#8]
Back again :)

I was able to get this to work locally by using specs, but what my team really cares about is getting retry working in Jenkins.

When I run in Jenkins, it looks like the retry is working:

Re-running tests , attempt :  1
 Re-running the following test files : /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js

But then I get the following error:

[15:26:37] E/launcher - Error: spawn /usr/bin/nodejs node_modules/protractor/bin/protractor ENOENT

It looks like the protractor binary in a non existent location, causing retry to fail. Do you have any ideas here?

**Comment by amrot17** [comment]
Hi , 

it would me more helpful if you can share the protractor command the the Jenkins is accepting, since we are building the retry command based on that command

for more reference this is where we start building the command 
https://github.com/yahoo/protractor-retry/blob/master/lib/retry.js#L70


[15:26:37] E/launcher - Error: spawn /usr/bin/nodejs node_modules/protractor/bin/protractor ENOENT
From this error, i see that the protractor path somehow received to the package in wrong format, so if you share the running command, this will help me debugging the issue 

Thanks

**Comment by emaxsaun** [comment]
Hi,

Thanks for the quick reply.

I have the protractor bin in the root of our project, here is the command that I run in Jenkins:

```
#!/usr/bin/env bash
cd regression-tests/protractor-tests && git clean -fdx
node -v
npm -v
npm install
npm install chromedriver
./node_modules/webdriver-manager/bin/webdriver-manager update --standalone true --versions.chrome 2.32
./protractor protractor.conf.js
```

Thanks,
-Ethan

**Comment by amrot17** [comment]
Hi ,

i think that the issue is on the ./ 
```
./protractor protractor.conf.js

```

can you try without the './' or if you can replace ./protractor with the the results of the executable path of protractor you can know that by running ''which protractor''  

```
which protractor 
or 
protractor protractor.conf.js
```


Thanks

**Comment by emaxsaun** [comment]
If I run this in Jenkins:

`protractor protractor.conf.js`

I get the following:

`/tmp/jenkins5609752487964907043.sh: line 9: protractor: command not found`

**Comment by amrot17** [comment]
what about 

```
./node_modules/.bin/protractor protractor.conf.js
```

**Comment by emaxsaun** [comment]
That might work, I will try this right now, thank you.

**Comment by emaxsaun** [comment]
Hm, it still didn't seem to work correctly.

My running command is:

`./node_modules/.bin/protractor protractor.conf.js`

But I get:

```
 Re-running tests , attempt :  1
 Re-running the following test files : /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js

[17:35:02] E/launcher - spawn /usr/bin/nodejs node_modules/.bin/protractor ENOENT
[17:35:02] E/launcher - Error: spawn /usr/bin/nodejs node_modules/.bin/protractor ENOENT
```

**Comment by amrot17** [comment]
same here 
I'm confused why it's looking for nodejs node_modules

lets debug more to this , can you run protractor with a debug mode 
```
 DEBUG=ProtractorRetry ./node_modules/.bin/protractor protractor.conf.js
```

you'll see some logs at the retry stage 
ProtractorRetry ProtractorCommand { _: [ './test/protractor.conf.js' ]

check for the  '$0' value 

it should be like below ( you may have another case we need to handle )
```
  '$0': 'node_modules/.bin/protractor' }
``` 

Thanks

**Comment by emaxsaun** [comment]
Testing now.

**Comment by emaxsaun** [comment]
Here is the log:

```
Automation Tests/regression-tests/protractor-tests/protractorFailuresReport/protractorTestErrors.xml

[18:09:33] I/testLogger - 

[18:09:33] I/launcher - 0 instance(s) of WebDriver still running
[18:09:33] I/launcher - chrome #01-0 passed
[18:09:33] I/launcher - chrome #01-1 failed 1 test(s)
[18:09:33] I/launcher - overall: 1 failed spec(s)
Thu, 02 Nov 2017 18:09:33 GMT ProtractorRetry resultsFile /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/protractorFailuresReport/protractorTestErrors.xml
Thu, 02 Nov 2017 18:09:33 GMT ProtractorRetry ProtractorCommand { _: [ 'protractor.conf.js' ],
  '$0': '/usr/bin/nodejs node_modules/.bin/protractor' }
Thu, 02 Nov 2017 18:09:33 GMT ProtractorRetry resultsFile /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/protractorFailuresReport/protractorTestErrors.xml
Thu, 02 Nov 2017 18:09:33 GMT ProtractorRetry resultsFile /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/protractorFailuresReport/protractorTestErrors-1.xml
Thu, 02 Nov 2017 18:09:33 GMT ProtractorRetry failedTestList [ { spec: [ '/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js,/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/node_modules/protractor/built/frameworks/__protractor_internal_afterEach_setup_spec.js' ] } ]


 Re-running tests , attempt :  1
 Re-running the following test files : /opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js


Thu, 02 Nov 2017 18:09:33 GMT ProtractorRetry Command /usr/bin/nodejs node_modules/.bin/protractor [ [ 'protractor.conf.js' ],
  '--specs',
  '/opt/jenkins_slave/workspace/Protractor Automation Tests/regression-tests/protractor-tests/ny-regressions/tests/checkListingsNumber.js',
  '--retry',
  1,
  '--disableChecks' ]
[18:09:33] E/launcher - spawn /usr/bin/nodejs node_modules/.bin/protractor ENOENT
[18:09:33] E/launcher - Error: spawn /usr/bin/nodejs node_modules/.bin/protractor ENOENT
```

**Comment by amrot17** [comment]
Im working on a solution for you , will let you know 

Thanks

**Comment by emaxsaun** [comment]
Thank you very much for your quick replies regarding this! Np!

**Comment by amrot17** [comment]
version @1.1.5 pushed now , it should fix the issue 
Please check and let me know

**Comment by emaxsaun** [comment]
Testing now!

**Comment by emaxsaun** [comment]
This fixed the problem! Thank you so much! This is resolved :)
